package com.webtextsearcher.ui.main;

public enum WebSearchStatus {
	SHOW_LOADER,
	HIDE_LOADER,
	URL_FORMAT_ERROR,
	THREAD_COUNT_ERROR,
	SEARCHED_TEXT_ERROR,
	MAX_SCAN_URL_ERROR,
	REMOVE_ALL_ERROR,
	ENABLE_VIEW,
	DISABLE_VIEW,
	PAUSE_ENABLE,
	PAUSE_DISABLE
}